language: python
python:
  - "3.8"
install:
  - pip install pipenv
  - pipenv install --system --deploy --dev

script:
  - python -m flake8
  - python -m mypy backend
  - python -m unittest discover .
