# Generated by Django 3.2.9 on 2021-11-21 01:26
from typing import List, Tuple

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Tuple[str, str]] = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('essentials', models.IntegerField()),
                ('education', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('retirement', models.IntegerField()),
                ('loose', models.IntegerField()),
            ],
            options={
                'db_table': 'budgets',
            },
        ),
    ]
