name: Tests
on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: password

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/personal-finance
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn
      - name: Run eslint validation
        run: yarn eslint .
  container-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker containers
        run: make build
      - name: Run frontend tests
        run: make linter
  python-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --system --deploy --dev
      - name: Type checking
        run: |
          python -m mypy api
      - name: Unit Tests
        run: |
          python -m unittest discover .
      - name: Django Tests
        working-directory: backend/api/personal_finances
          run: |
            python -m unittest discover .